// run-ladder.mjs — SELF-PLAY RUNGS (the connect4/ga4444 DNA): each learner's
// best becomes the next's sparring partner. Rung 0 bar = hunter's TRAIN mean
// (the strongest baseline). Rungs in order: q-table → tiny-nn → ga-params →
// memory-walker. A rung takes the title (champion) only if its TRAIN mean
// strictly beats the current holder's; the holder it beat is receipted. Runs
// hunter + memory-walker on TRAIN seeds (the other learners' TRAIN receipts
// already exist from their tools), reads results/train-scores.jsonl, writes
// results/ladder.json and the GENERATED learners/ladder.js champion wrapper.
import { writeFileSync } from 'node:fs';
import { runGame, TRAIN_SEEDS, appendTrain, readScores, TRAIN_PATH, canonicalJSON } from './common.mjs';
import hunterFactory from '../core/scripts/hunter.js';
import memoryWalkerFactory from '../learners/memory-walker.js';

for (const seed of TRAIN_SEEDS) appendTrain('hunter(TRAIN)', seed, runGame(hunterFactory, seed));
for (const seed of TRAIN_SEEDS) appendTrain('memory-walker(TRAIN)', seed, runGame(memoryWalkerFactory, seed));

const recs = readScores(TRAIN_PATH);
const meanOf = name => {
  const rs = recs.filter(r => r.script === name);
  if (rs.length !== TRAIN_SEEDS.length) throw new Error(`${name}: ${rs.length} receipts, expected ${TRAIN_SEEDS.length}`);
  return rs.reduce((n, r) => n + r.score, 0) / rs.length;
};

const ORDER = ['q-table', 'tiny-nn', 'ga-params', 'memory-walker'];
let holder = { name: 'hunter', mean: meanOf('hunter(TRAIN)') };
const rungs = [];
for (const learner of ORDER) {
  const mean = meanOf(`${learner}(TRAIN)`);
  const beat = mean > holder.mean;
  const vs = holder;
  if (beat) holder = { name: learner, mean };
  rungs.push({ rung: rungs.length + 1, learner, trainMean: +mean.toFixed(2), sparredAgainst: vs.name, vsMean: +vs.mean.toFixed(2), beat });
}
const ladder = { bar0: { name: 'hunter', trainMean: +meanOf('hunter(TRAIN)').toFixed(2) }, rungs, champion: holder.name, championTrainMean: +holder.mean.toFixed(2) };
writeFileSync(new URL('../results/ladder.json', import.meta.url), JSON.stringify(ladder, null, 1) + '\n');

const gen = `// ladder.js — GENERATED by tools/run-ladder.mjs (do not hand-edit).
// Self-play rungs: hunter(bar) → ${ORDER.join(' → ')}. A rung took the title
// only when its TRAIN mean strictly beat the holder's (results/ladder.json is
// the receipt: which rung beat which). Champion by succession: ${ladder.champion}.
import qTable from './q-table.js';
import tinyNn from './tiny-nn.js';
import gaParams from './ga-params.js';
import memoryWalker from './memory-walker.js';
const CHAMPIONS = { 'q-table': qTable, 'tiny-nn': tinyNn, 'ga-params': gaParams, 'memory-walker': memoryWalker };
export const CHAMPION = ${JSON.stringify(ladder.champion)};
export default function ladder(seed) {
  const inner = CHAMPIONS[CHAMPION](seed);
  return { name: 'ladder→' + inner.name, step: (percept, memory) => inner.step(percept, memory) };
}
`;
writeFileSync(new URL('../learners/ladder.js', import.meta.url), gen);
console.log(canonicalJSON(ladder));
