// ladder.js — GENERATED by tools/run-ladder.mjs (do not hand-edit).
// Self-play rungs: hunter(bar) → q-table → tiny-nn → ga-params → memory-walker. A rung took the title
// only when its TRAIN mean strictly beat the holder's (results/ladder.json is
// the receipt: which rung beat which). Champion by succession: memory-walker.
import qTable from './q-table.js';
import tinyNn from './tiny-nn.js';
import gaParams from './ga-params.js';
import memoryWalker from './memory-walker.js';
const CHAMPIONS = { 'q-table': qTable, 'tiny-nn': tinyNn, 'ga-params': gaParams, 'memory-walker': memoryWalker };
export const CHAMPION = "memory-walker";
export default function ladder(seed) {
  const inner = CHAMPIONS[CHAMPION](seed);
  return { name: 'ladder→' + inner.name, step: (percept, memory) => inner.step(percept, memory) };
}
